# Generated by Django 5.2.1 on 2025-05-26 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='is_verified_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
